# Site Settings
lang: en
title: Daniela A. Gonzalez
tagline: Daniela A. Gonzalez
email: daniela.gonzalez@unc.edu.ar
description: >
  Daniela A. Gonzalez personal website
baseurl: ""
url: "agdaniela.github.io"
permalink: pretty
#favicon: /path/to/favicon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#9d848e' also change assets/css/app.scss
theme_color: '#6d6ea4'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: light

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
#cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
